# Generated by Django 4.2.1 on 2023-05-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizquestion_option1points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avengername', models.CharField(max_length=50)),
                ('avengerdes', models.TextField()),
                ('avengerimg', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
